# render.yaml

services:
  - type: worker
    name: tgrobotic-bot
    env: python
    repo: https://github.com/tgrobotic1000/Tgrobotic.git
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: API_ID
        value: "25165349"
      - key: API_HASH
        value: "d5ea503a893548d7d492f91fc72e8ce9"
      - key: BOT_TOKEN
        value: "7729291712:AAEyuIgE7VLStp1tpZrKiEVrTFFjUujZJks"
      - key: CHID
        value: "-1002662027422"
      - key: SUDO
        value: "7439650239"
      - key: MONGO_URI
        value: "mongodb+srv://tgrobotic:nRUEU81Zc3r5gMxK@cluster0.omkktyb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
